camel:
  springboot:
    main-run-controller: true
    name: camel-context-honesto-sqn
  component:
    telegram:
      authorization-token: 503244464:AAHjAiIUskr4jpicDJ8vEUpHz0pZ3SjjK-Q

spring:
    application:
        name: honesto-sqn
    main:
        banner-mode: "off"
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop         
    security:
        enabled: false

serenata:
    jarbas:
        endpoint: https://jarbas.serenata.ai